### PR TITLE
mukube: Add over-the-air updating comparison doc

### PR DESCRIPTION
**Pull request by klausenbusk**
Rendered: https://github.com/distributed-technologies/SCCP-documentation/blob/feature/ota-doc/mukube/ota-updating.md

### CODE REVIEW

**Review by SomeFriendlyGhost — APPROVED** [review]
LGTM

**Review by skovbakke — APPROVED** [review]
LGTM. This is a good starting point.

**Review by skovbakke — APPROVED** [review]
LGTM 🥳

**Review by SomeFriendlyGhost — APPROVED** [review]
The new section looks good

**Pull request merged**
